### ISSUE TITLE
working with new Kubernetes node

### ISSUE THREAD

**Issue by JR-Utily** [trion-development/docker-jenkins-docker-client#5]
Hello,

We based our CI environment on this project, deploying our jenkins in a GKE k8s cluster, and building our docker image artifacts from there in shell jenkins job that were using directly `docker build` and `docker push`.

The problem is that since a last upgrade [ https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/ ], the docker socket is not available on the node anymore. 

Do you know if there is a workaround to keep our pipeline as close as possible from what was working a couple of weeks ago without a sudden need to re-design everything ? 

I've seen people talking about kaniko and stuff, but we don't like the idea of having a build process that would not be reproducible in our local dev machine :/ Until now, it was exactly the exact same script that was used to build in a local dev env or in the CI env, and so it make it very smooth to modify and test them.

**Comment by everflux** [comment]
Sure, you can keep your current setup in principle.
In general I suggest to *not* use the docker socket from the node anyway.

Just run a docker daemon as a sidecar container and it is available on localhost. Or you use a separate pod to provide the docker daemon.

Does that solve your issue?

**Comment by JR-Utily** [comment]
Thanks for your quick reply. 
You mean something like that ?

```
spec:
  containers:
  - image: docker:dind
    name: docker-daemon
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  - image: trion/jenkins-docker-client
    name: jenkins
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  volumes:
  - name: docker-socket
    emptyDir: {}
```

but if the socket is not declared as a hostPath, wouldn't it miss the information that this *is* a socket ?

**Comment by everflux** [comment]
Interesting idea to use a volume mount for the socket. That might work!
I usually use a TCP socket with an environment variable `DOCKER_HOST="tcp://127.0.0.1:2375"`

If you are looking into `jib` to build images, you might be interested in https://hub.docker.com/r/trion/jib-cli as well. But docker usually is not only used to build images, so there is still a use case for the docker sidecar with jenkins integration.

**Comment by JR-Utily** [comment]
Well, the volume mount was suggested by the command line you give as example in the README.

I was not aware it is possible to access docker through tcp :) 
This is much simpler:

```
spec:
  containers:
  - image: docker:dind
    name: docker-daemon
  - image: trion/jenkins-docker-client
    name: jenkins
    env:
    - name: DOCKER_HOST
      value: "tcp://0.0.0.0:2375"
```
and that's it ?
